/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.Tgpalmas.ui;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import mx.itson.Tgpalmas.entities.AccountHolder;
import mx.itson.Tgpalmas.entities.BankAccount;
import mx.itson.Tgpalmas.entities.Transaction;

/**
 *
 * @author luisantoniocamparubio
 */
public class bankFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public bankFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnfile = new javax.swing.JButton();
        lblproduct = new javax.swing.JLabel();
        lblccountNumber = new javax.swing.JLabel();
        lblcurrency = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccountHolder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltransactions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnfile.setText("Selec file ");
        btnfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfileActionPerformed(evt);
            }
        });

        lblproduct.setBackground(new java.awt.Color(0, 0, 204));
        lblproduct.setFont(new java.awt.Font("Beirut", 0, 36)); // NOI18N
        lblproduct.setText("...");

        lblccountNumber.setBackground(new java.awt.Color(0, 0, 255));
        lblccountNumber.setFont(new java.awt.Font("Beirut", 0, 24)); // NOI18N
        lblccountNumber.setText("...");

        lblcurrency.setBackground(new java.awt.Color(204, 0, 51));
        lblcurrency.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        lblcurrency.setForeground(new java.awt.Color(204, 0, 0));
        lblcurrency.setText("...");

        tblAccountHolder.setBackground(new java.awt.Color(255, 255, 255));
        tblAccountHolder.setFont(new java.awt.Font("Beirut", 0, 8)); // NOI18N
        tblAccountHolder.setForeground(new java.awt.Color(0, 0, 0));
        tblAccountHolder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODE", "NAME", "ADDRESS", "CITY", "TAXPAYER ID", "ZIPCODE"
            }
        ));
        jScrollPane1.setViewportView(tblAccountHolder);

        tbltransactions.setBackground(new java.awt.Color(255, 255, 255));
        tbltransactions.setForeground(new java.awt.Color(0, 0, 0));
        tbltransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DATE", "DESCRIPTION", "REFERENCE", "AMOUNT", "TYPE"
            }
        ));
        jScrollPane2.setViewportView(tbltransactions);

        jLabel2.setFont(new java.awt.Font("Beirut", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Transactions made from your account");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Beirut", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Personal data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnfile)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnfile)
                .addGap(22, 22, 22)
                .addComponent(lblproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcurrency)
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfileActionPerformed
FileDialog fileDialog = new FileDialog(this, "Select file", FileDialog.LOAD);
                fileDialog.setVisible(true);

                String directory = fileDialog.getDirectory();
                String filename = fileDialog.getFile();

                if (filename != null) {
                    File selectedFile = new File(directory, filename);
                    try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                        StringBuilder content = new StringBuilder();
                        String line;
                        while ((line = reader.readLine()) != null) {
                            content.append(line).append("\n");
                        }
                        String contenido = content.toString();
                       BankAccount a = BankAccount.desearelizar(contenido);
                       lblproduct.setText(a.getProduct());
                       lblccountNumber.setText("Account Number: "+ a.getAccountNumber());
                       lblcurrency.setText("Currency: "+ a.getCurrency());
                        
                       AccountHolder h = a.getAccountHolder();
                       DefaultTableModel modelo = (DefaultTableModel) tblAccountHolder.getModel();
                       modelo.setRowCount(0); 
                       modelo.addRow(new Object[]{                      
                        h.getCode(),
                        h.getName(),
                        h.getAddress(),
                        h.getCity(),
                        h.getTaxpayerId(),
                        h.getZipCode()
                        });
                       
                    DefaultTableModel model =(DefaultTableModel) tbltransactions.getModel();
                     model.setRowCount(0);
                     List<Transaction> trans = new ArrayList<>( a.getTransactions() );
                     trans.sort( Comparator.comparing(Transaction::getDate) );
                     SimpleDateFormat dateFormat= new SimpleDateFormat("dd'/'MM'/'yyyy");
                     for (Transaction t : trans) {
                     model.addRow(new Object[]{
                     dateFormat.format(t.getDate()),
                     t.getDescription(),
                     t.getReference(),
                     "$" + t.getAmount(),
                     t.getType(),                           
                            });                  
        }
                      

                       
                    
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }        // TODO add your handling code here:
    }//GEN-LAST:event_btnfileActionPerformed

    /** Main method to initialize and display the application UI
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bankFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblccountNumber;
    private javax.swing.JLabel lblcurrency;
    private javax.swing.JLabel lblproduct;
    private javax.swing.JTable tblAccountHolder;
    private javax.swing.JTable tbltransactions;
    // End of variables declaration//GEN-END:variables
}
